sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  redis:
    host: 192.168.10.3
    password: 123456
    port: 6379
    database: 2
  wechat:
    appid: wx1597e2890ca86d67
    secret: bbdf1f2e271b26ff5043dfc52d302a71

